# Generated by Django 5.1 on 2024-08-19 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='relation_to',
            field=models.IntegerField(choices=[(0, 'outerwear'), (1, 'underwear'), (2, 'accessories'), (3, 'shoes')]),
        ),
        migrations.AlterField(
            model_name='products',
            name='images_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.images'),
        ),
    ]
