# Generated by Django 5.1 on 2024-08-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_categories_relation_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='reviews',
            field=models.JSONField(null=True),
        ),
    ]
