# Generated by Django 5.1 on 2024-08-20 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_products_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='categories_fk',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sizes_fk',
        ),
        migrations.AddField(
            model_name='categories',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='api.products'),
        ),
        migrations.AddField(
            model_name='sizes',
            name='products_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sizes', to='api.products'),
        ),
    ]
