# Generated by Django 5.1 on 2024-09-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_products_categories_fk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='id',
            new_name='cat_id_pk',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='products',
            new_name='products_fk',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='id',
            new_name='prod_id_pk',
        ),
        migrations.RenameField(
            model_name='sizes',
            old_name='id',
            new_name='size_id_pk',
        ),
    ]
